import marimo

__generated_with = "0.16.5"
app = marimo.App()


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Taking Responsibility Essay
    The writer emphasises the grip that large tech companies have on populations of countries, and how as a result it has placed quite invasive manoeuvres to allow private information from citizens to be used at an unregulated scale to make large profits. Both China’s Social Credit System and Uruguay’s emerging approach to taxing digital transactions reflect how contemporary governments attempt to manage, regulate, and benefit from the digital data generated by their citizens. These two cases illustrate different models for governmental intervention in the digital economy, each with distinct motivations and consequences.

    The writer concurs frequently how information is unquantifiable in comparison to the value of money known as “a universal measurer”, and so it can be inferred that those who are able to control the information first have access to a new currency, henceforth a monopoly on this new sector which can be both positive and negative towards civilian’s long term. An example described is Google and Byte dances involvement in Uruguay. Seen as quite invasive, these global tech firms provide Uruguayan citizens with free services in exchange for valuable personal data including: purchase histories, photos, and online content. This information was then used to train artificial intelligence systems, which were then marketed to governments and corporations worldwide to be bought. However, despite this initial perceived invasion of privacy, the Uruguayan government found a way to combat this exploitation in the form of a tax scheme to at least profit from this usage by capturing revenue from digital transactions, as in reality the option to decline these services outweighs the time and budget allocation needed to support and craft these services at a national scale. Therefore, this case highlighted by the writer certainly provokes the reader in thought to the benefits of digital services with the economic and ethical implications of mass data collection and commercialization.
    
    In stark contrast we have the mention of Chinas Social Credit System, this here shows these invasive techniques seen with big tech orgs previously, now provided by the government rather than industry; certainly, increasing the perceived value of information as the state is shown to want this information at all costs. China’s Social Credit System was established to enhance societal trustworthiness, legal compliance, and social order. It functions by integrating data from government agencies, financial records, legal documents, and online platforms, producing a “credit score” for individuals and enterprises based on their behaviour. At its core, China’s model is an extensive, internally focused system of governance, where the government exercises direct control over the use and purpose of collected data, intending to shape citizen behaviour through both incentives and deterrents. In contrast, Uruguay’s strategy is externally focused, seeking to reclaim some measure of control and financial benefit from foreign companies profiting from locally generated data. Privacy concerns exist in both models, but the locus of power differs: China’s system is government-driven, while Uruguay’s issues revolve around the influence of multinational corporations and global data flows.
    
    Although both systems reflect the increasing centrality of data in governance and economics, the Chinese Social Credit System (CSCS) and Uruguay's proposed digital transaction tax represent distinct policy responses shaped by differing national priorities. China’s approach is behavioural and regulatory, leveraging data to enforce social norms at home. Uruguay’s strategy is economic and defensive, designed to address the power asymmetries of the global digital marketplace. As societies grapple with the profound implications of data-driven technologies, these cases offer contrasting visions for the future relationship between citizens, governments, and technology companies. Circling back to the writers’ intentions, despite the extract not going into detail on the CSCS, it is clear this is where the writer was leading to, how despite the monopolisation of information is being spearheaded by big tech, there is also the control and ‘spying’ aspect being forefront with China as well as how their tax is penalties under the social credit system (blacklisting), not monetary but social.


    ## Additional Research: Found using Perplexity AI
    1.	https://hellopebl.com/resources/blog/chinese-social-credit-system/
    2.	https://orcasia.org/chinas-social-credit-system
    """
    )
    return


if __name__ == "__main__":
    app.run()
